# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

$script = <<EOF
echo "I am provisioning"
sudo rpm -iUvh /vagrant/jdk-7*
unzip /vagrant/sonarqube-4.3.zip -d /home/vagrant
unzip /vagrant/JavaEcosystem-2.2.1.zip -d /home/vagrant/sonarqube-4.3/extensions/plugins
sudo rpm -iUvh /vagrant/jenkins*
sudo /etc/init.d/jenkins start
sudo chkconfig jenkins on
EOF

$startservices = <<EOF
/home/vagrant/sonarqube-4.3/bin/linux-x86-64/sonar.sh start
EOF

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "centos65"
  # config.vm.box_check_update = false

  config.vm.network "forwarded_port", guest: 9000, host: 9000
  config.vm.network "forwarded_port", guest: 8080, host: 9080

  # config.vm.network "private_network", ip: "192.168.33.10"
  # config.vm.network "public_network"
  # config.ssh.forward_agent = true
  # config.vm.synced_folder "../data", "/vagrant_data"
  
  config.vm.provider "virtualbox" do |vb|
     # Use VBoxManage to customize the VM. For example to change memory:
     vb.customize ["modifyvm", :id, "--memory", "1024"]
  end
  
  config.vm.hostname = "devbox"
  
  config.vm.provision "shell", inline: $script
  config.vm.provision "shell", inline: $startservices, run: "always"
  
  #config.vm.provision "puppet" do |puppet|
  #  puppet.manifests_path = "manifests"
  #  puppet.manifest_file  = "site.pp"
  #end


end
